KSquirrel 0.7.2 sources

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1666,6 +1666,8 @@ Optional Features:
   --disable-threading     disables threading even if libpthread found
   --disable-rpath         do not use the rpath feature of ld
   --disable-path-check    don't try to find out, where to install
+  --disable-kipi          don't search for KIPI plugins [default=no]
+  --disable-kexif         don't search for KEXIF [default=no]
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -2635,7 +2637,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=ksquirrel
- VERSION=0.7.1
+ VERSION=0.7.2
 
 
 cat >>confdefs.h <<_ACEOF
@@ -8426,7 +8428,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 8429 "configure"' > conftest.$ac_ext
+  echo '#line 8431 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -10167,11 +10169,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10170: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10172: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10174: \$? = $ac_status" >&5
+   echo "$as_me:10176: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10400,11 +10402,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10403: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10405: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10407: \$? = $ac_status" >&5
+   echo "$as_me:10409: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10467,11 +10469,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10470: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10472: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10474: \$? = $ac_status" >&5
+   echo "$as_me:10476: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12553,7 +12555,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12556 "configure"
+#line 12558 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12651,7 +12653,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12654 "configure"
+#line 12656 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14812,11 +14814,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14815: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14817: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14819: \$? = $ac_status" >&5
+   echo "$as_me:14821: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14879,11 +14881,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14882: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14884: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14886: \$? = $ac_status" >&5
+   echo "$as_me:14888: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16182,7 +16184,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16185 "configure"
+#line 16187 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16280,7 +16282,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16283 "configure"
+#line 16285 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17103,11 +17105,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17106: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17108: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17110: \$? = $ac_status" >&5
+   echo "$as_me:17112: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17170,11 +17172,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17173: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17175: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17177: \$? = $ac_status" >&5
+   echo "$as_me:17179: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19138,11 +19140,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19141: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19143: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19145: \$? = $ac_status" >&5
+   echo "$as_me:19147: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -19371,11 +19373,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19374: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19376: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19378: \$? = $ac_status" >&5
+   echo "$as_me:19380: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -19438,11 +19440,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19441: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19443: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19445: \$? = $ac_status" >&5
+   echo "$as_me:19447: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21524,7 +21526,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 21527 "configure"
+#line 21529 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21622,7 +21624,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 21625 "configure"
+#line 21627 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -30110,7 +30112,7 @@ for i in $jpeg_incdirs;
 do
   for j in jpeglib.h;
   do
-    echo "configure: 30113: $i/$j" >&5
+    echo "configure: 30115: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       jpeg_incdir=$i
@@ -30408,7 +30410,7 @@ for i in $qt_incdirs;
 do
   for j in $kde_qt_header;
   do
-    echo "configure: 30411: $i/$j" >&5
+    echo "configure: 30413: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       qt_incdir=$i
@@ -31239,7 +31241,7 @@ for i in $kde_incdirs;
 do
   for j in $kde_check_header;
   do
-    echo "configure: 31242: $i/$j" >&5
+    echo "configure: 31244: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_incdir=$i
@@ -31269,7 +31271,7 @@ for i in $kde_libdirs;
 do
   for j in $kde_check_lib;
   do
-    echo "configure: 31272: $i/$j" >&5
+    echo "configure: 31274: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_libdir=$i
@@ -31287,7 +31289,7 @@ for i in $kde_libdirs;
 do
   for j in "kde3/plugins/designer/kdewidgets.la";
   do
-    echo "configure: 31290: $i/$j" >&5
+    echo "configure: 31292: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_widgetdir=$i
@@ -32806,7 +32808,7 @@ for i in $kde_sharedirs;
 do
   for j in apps/ksgmltools2/customization/kde-chunk.xsl;
   do
-    echo "configure: 32809: $i/$j" >&5
+    echo "configure: 32811: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       KDE_XSL_STYLESHEET=$i
@@ -32963,6 +32965,34 @@ fi
 
 
 #MIN_CONFIG(3.3)
+
+
+sq_kipi="yes"
+# Check whether --enable-kipi was given.
+if test "${enable_kipi+set}" = set; then
+  enableval=$enable_kipi;      case "${enableval}" in
+                       yes) sq_kipi="yes" ;;
+                       no)  sq_kipi="no" ;;
+                       *)   { { echo "$as_me:$LINENO: error: bad value ${enableval} for this parameter" >&5
+echo "$as_me: error: bad value ${enableval} for this parameter" >&2;}
+   { (exit 1); exit 1; }; } ;;
+                    esac
+
+fi
+
+
+sq_kexif="yes"
+# Check whether --enable-kexif was given.
+if test "${enable_kexif+set}" = set; then
+  enableval=$enable_kexif;      case "${enableval}" in
+                       yes) sq_kexif="yes" ;;
+                       no)  sq_kexif="no" ;;
+                       *)   { { echo "$as_me:$LINENO: error: bad value ${enableval} for this parameter" >&5
+echo "$as_me: error: bad value ${enableval} for this parameter" >&2;}
+   { (exit 1); exit 1; }; } ;;
+                    esac
+
+fi
 
 
 if test "${ac_cv_header_utime_h+set}" = set; then
@@ -34471,6 +34501,7 @@ KSQUIRREL_ASM_DEFS="$ksquirrel_asm_defs"
 # KIPI
 #
 have_kipi=no
+if test x$sq_kipi = xyes; then
 
 pkg_failed=no
 { echo "$as_me:$LINENO: checking for libkipi" >&5
@@ -34545,10 +34576,10 @@ else
         { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 
-        _cppflags=$CPPFLAGS
+        _cxxflags=$CXXFLAGS
         _ldflags=$LDFLAGS
 
-        CPPFLAGS="$libkipi_CFLAGS $CPPFLAGS"
+        CXXFLAGS="$libkipi_CFLAGS $CXXFLAGS"
         LDFLAGS="$LDFLAGS $libkipi_LIBS"
 
 
@@ -34715,15 +34746,17 @@ _ACEOF
 echo "$as_me: WARNING: Can't find KIPI headers, KSquirrel won't be compiled with KIPI support" >&2;}
           fi
 
-            CPPFLAGS=$_cppflags
+            CXXFLAGS=$_cxxflags
             LDFLAGS=$_ldflags
 
+fi
 fi
 
 #
 # KEXIF
 #
 have_kexif=no
+if test x$sq_kexif = xyes; then
 
 pkg_failed=no
 { echo "$as_me:$LINENO: checking for libkexif" >&5
@@ -34798,10 +34831,10 @@ else
         { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 
-        _cppflags=$CPPFLAGS
+        _cxxflags=$CXXFLAGS
         _ldflags=$LDFLAGS
 
-        CPPFLAGS="$libkexif_CFLAGS $CPPFLAGS"
+        CXXFLAGS="$libkexif_CFLAGS $CXXFLAGS"
         LDFLAGS="$LDFLAGS $libkexif_LIBS"
 
 
@@ -34968,9 +35001,10 @@ _ACEOF
 echo "$as_me: WARNING: Can't find KEXIF headers, KSquirrel won't be compiled with KEXIF support" >&2;}
           fi
 
-            CPPFLAGS=$_cppflags
+            CXXFLAGS=$_cxxflags
             LDFLAGS=$_ldflags
 
+fi
 fi
 
  if test x$have_kipi  = xyes; then
@@ -36711,6 +36745,21 @@ if test "$no_create" != yes; then
   $ac_cs_success || { (exit 1); exit 1; }
 fi
 
+echo
+echo "Results:"
+echo "--------"
+echo
+echo "Version:        ${VERSION}"
+echo
+echo "Compiler:       ${CC}"
+echo "CXXFLAGS:       ${CXXFLAGS}"
+echo
+echo "Prefix:         ${prefix}"
+echo "KDE prefix:     ${kde_libs_prefix}"
+echo
+echo "KIPI  support:  ${have_kipi}"
+echo "KEXIF support:  ${have_kexif}"
+echo "ASM flags:      ${KSQUIRREL_ASM_DEFS}"
 # Check if KDE_SET_PREFIX was called, and --prefix was passed to configure
 if test -n "$kde_libs_prefix" -a -n "$given_prefix"; then
   # And if so, warn when they don't match
