KSquirrel 0.8.0 sources

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1011,6 +1011,10 @@ LIB_KUNITTEST
 LIB_KSYCOCA
 LIB_KFILE
 LIB_KFM
+SQ_HAVE_KPART_TRUE
+SQ_HAVE_KPART_FALSE
+SQ_HAVE_KLCONF_TRUE
+SQ_HAVE_KLCONF_FALSE
 PKG_CONFIG
 ksquirrellibs_CFLAGS
 ksquirrellibs_LIBS
@@ -1668,6 +1672,11 @@ Optional Features:
   --disable-path-check    don't try to find out, where to install
   --disable-kipi          don't search for KIPI plugins [default=no]
   --disable-kexif         don't search for KEXIF [default=no]
+  --disable-kpart         don't compile Konqueror integration (KPart object)
+                          [default=no]
+  --disable-ksquirrel-libs-configurator
+                          don't compile ksquirrel-libs configurator
+                          [default=no]
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -2637,7 +2646,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=ksquirrel
- VERSION=0.7.5
+ VERSION=0.8.0
 
 
 cat >>confdefs.h <<_ACEOF
@@ -8428,7 +8437,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 8431 "configure"' > conftest.$ac_ext
+  echo '#line 8440 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -10169,11 +10178,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10172: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10181: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10176: \$? = $ac_status" >&5
+   echo "$as_me:10185: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10402,11 +10411,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10405: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10414: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10409: \$? = $ac_status" >&5
+   echo "$as_me:10418: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10469,11 +10478,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10472: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10481: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10476: \$? = $ac_status" >&5
+   echo "$as_me:10485: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12555,7 +12564,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12558 "configure"
+#line 12567 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12653,7 +12662,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12656 "configure"
+#line 12665 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14814,11 +14823,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14817: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14826: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14821: \$? = $ac_status" >&5
+   echo "$as_me:14830: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14881,11 +14890,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14884: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14893: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14888: \$? = $ac_status" >&5
+   echo "$as_me:14897: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16184,7 +16193,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16187 "configure"
+#line 16196 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16282,7 +16291,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16285 "configure"
+#line 16294 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17105,11 +17114,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17108: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17117: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17112: \$? = $ac_status" >&5
+   echo "$as_me:17121: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17172,11 +17181,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17175: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17184: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17179: \$? = $ac_status" >&5
+   echo "$as_me:17188: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19140,11 +19149,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19143: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19152: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19147: \$? = $ac_status" >&5
+   echo "$as_me:19156: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -19373,11 +19382,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19376: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19385: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19380: \$? = $ac_status" >&5
+   echo "$as_me:19389: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -19440,11 +19449,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19443: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19452: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19447: \$? = $ac_status" >&5
+   echo "$as_me:19456: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21526,7 +21535,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 21529 "configure"
+#line 21538 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21624,7 +21633,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 21627 "configure"
+#line 21636 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -29780,6 +29789,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
 #include<zlib.h>
+#include<string.h>
 
 int
 main ()
@@ -29790,7 +29800,7 @@ main ()
   /* this would segfault.. but we only link, don't run */
   (void) gzgets(f, buf, sizeof(buf));
 
-  return (zlibVersion() == ZLIB_VERSION);
+  return (strcmp(zlibVersion(), ZLIB_VERSION) == 0);
 
   ;
   return 0;
@@ -30112,7 +30122,7 @@ for i in $jpeg_incdirs;
 do
   for j in jpeglib.h;
   do
-    echo "configure: 30115: $i/$j" >&5
+    echo "configure: 30125: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       jpeg_incdir=$i
@@ -30410,7 +30420,7 @@ for i in $qt_incdirs;
 do
   for j in $kde_qt_header;
   do
-    echo "configure: 30413: $i/$j" >&5
+    echo "configure: 30423: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       qt_incdir=$i
@@ -31241,7 +31251,7 @@ for i in $kde_incdirs;
 do
   for j in $kde_check_header;
   do
-    echo "configure: 31244: $i/$j" >&5
+    echo "configure: 31254: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_incdir=$i
@@ -31271,7 +31281,7 @@ for i in $kde_libdirs;
 do
   for j in $kde_check_lib;
   do
-    echo "configure: 31274: $i/$j" >&5
+    echo "configure: 31284: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_libdir=$i
@@ -31289,7 +31299,7 @@ for i in $kde_libdirs;
 do
   for j in "kde3/plugins/designer/kdewidgets.la";
   do
-    echo "configure: 31292: $i/$j" >&5
+    echo "configure: 31302: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_widgetdir=$i
@@ -32808,7 +32818,7 @@ for i in $kde_sharedirs;
 do
   for j in apps/ksgmltools2/customization/kde-chunk.xsl;
   do
-    echo "configure: 32811: $i/$j" >&5
+    echo "configure: 32821: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       KDE_XSL_STYLESHEET=$i
@@ -32995,6 +33005,53 @@ echo "$as_me: error: bad value ${enableval} for this parameter" >&2;}
 fi
 
 
+have_kpart="yes"
+# Check whether --enable-kpart was given.
+if test "${enable_kpart+set}" = set; then
+  enableval=$enable_kpart;      case "${enableval}" in
+                       yes) ;;
+                       no)  have_kpart="no" ;;
+                       *)   { { echo "$as_me:$LINENO: error: bad value ${enableval} for this parameter" >&5
+echo "$as_me: error: bad value ${enableval} for this parameter" >&2;}
+   { (exit 1); exit 1; }; } ;;
+                    esac
+
+fi
+
+
+ if test x$have_kpart  = xyes; then
+  SQ_HAVE_KPART_TRUE=
+  SQ_HAVE_KPART_FALSE='#'
+else
+  SQ_HAVE_KPART_TRUE='#'
+  SQ_HAVE_KPART_FALSE=
+fi
+
+
+have_klconf="yes"
+# Check whether --enable-ksquirrel-libs-configurator was given.
+if test "${enable_ksquirrel_libs_configurator+set}" = set; then
+  enableval=$enable_ksquirrel_libs_configurator;      case "${enableval}" in
+                       yes) ;;
+                       no)  have_klconf="no" ;;
+                       *)   { { echo "$as_me:$LINENO: error: bad value ${enableval} for this parameter" >&5
+echo "$as_me: error: bad value ${enableval} for this parameter" >&2;}
+   { (exit 1); exit 1; }; } ;;
+                    esac
+
+fi
+
+
+ if test x$have_klconf  = xyes; then
+  SQ_HAVE_KLCONF_TRUE=
+  SQ_HAVE_KLCONF_FALSE='#'
+else
+  SQ_HAVE_KLCONF_TRUE='#'
+  SQ_HAVE_KLCONF_FALSE=
+fi
+
+
+# utime.h
 if test "${ac_cv_header_utime_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for utime.h" >&5
 echo $ECHO_N "checking for utime.h... $ECHO_C" >&6; }
@@ -33643,8 +33700,8 @@ fi
 if test $ac_cv_header_konq_operations_h = yes; then
   :
 else
-  { { echo "$as_me:$LINENO: error: \"Header file konq_operations.h is missing. Please install kdebase-devel package.\"" >&5
-echo "$as_me: error: \"Header file konq_operations.h is missing. Please install kdebase-devel package.\"" >&2;}
+  { { echo "$as_me:$LINENO: error: \"Header file konq_operations.h is missing. Please install libkonq-devel package.\"" >&5
+echo "$as_me: error: \"Header file konq_operations.h is missing. Please install libkonq-devel package.\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -35079,6 +35136,10 @@ ac_config_files="$ac_config_files ksquirrel/Makefile"
 
 ac_config_files="$ac_config_files ksquirrel/imageedit/Makefile"
 
+ac_config_files="$ac_config_files ksquirrel/ksquirrel-libs-configurator/Makefile"
+
+ac_config_files="$ac_config_files ksquirrel/ksquirrelpart/Makefile"
+
 ac_config_files="$ac_config_files ksquirrel/mime/Makefile"
 
 ac_config_files="$ac_config_files ksquirrel/sidebar/Makefile"
@@ -35228,6 +35289,20 @@ if test -z "${include_ARTS_TRUE}" && test -z "${include_ARTS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"include_ARTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"include_ARTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SQ_HAVE_KPART_TRUE}" && test -z "${SQ_HAVE_KPART_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SQ_HAVE_KPART\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SQ_HAVE_KPART\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SQ_HAVE_KLCONF_TRUE}" && test -z "${SQ_HAVE_KLCONF_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SQ_HAVE_KLCONF\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SQ_HAVE_KLCONF\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -35726,6 +35801,8 @@ do
     "doc/ru/Makefile") CONFIG_FILES="$CONFIG_FILES doc/ru/Makefile" ;;
     "ksquirrel/Makefile") CONFIG_FILES="$CONFIG_FILES ksquirrel/Makefile" ;;
     "ksquirrel/imageedit/Makefile") CONFIG_FILES="$CONFIG_FILES ksquirrel/imageedit/Makefile" ;;
+    "ksquirrel/ksquirrel-libs-configurator/Makefile") CONFIG_FILES="$CONFIG_FILES ksquirrel/ksquirrel-libs-configurator/Makefile" ;;
+    "ksquirrel/ksquirrelpart/Makefile") CONFIG_FILES="$CONFIG_FILES ksquirrel/ksquirrelpart/Makefile" ;;
     "ksquirrel/mime/Makefile") CONFIG_FILES="$CONFIG_FILES ksquirrel/mime/Makefile" ;;
     "ksquirrel/sidebar/Makefile") CONFIG_FILES="$CONFIG_FILES ksquirrel/sidebar/Makefile" ;;
     "pics/Makefile") CONFIG_FILES="$CONFIG_FILES pics/Makefile" ;;
@@ -36120,6 +36197,10 @@ LIB_KUNITTEST!$LIB_KUNITTEST$ac_delim
 LIB_KSYCOCA!$LIB_KSYCOCA$ac_delim
 LIB_KFILE!$LIB_KFILE$ac_delim
 LIB_KFM!$LIB_KFM$ac_delim
+SQ_HAVE_KPART_TRUE!$SQ_HAVE_KPART_TRUE$ac_delim
+SQ_HAVE_KPART_FALSE!$SQ_HAVE_KPART_FALSE$ac_delim
+SQ_HAVE_KLCONF_TRUE!$SQ_HAVE_KLCONF_TRUE$ac_delim
+SQ_HAVE_KLCONF_FALSE!$SQ_HAVE_KLCONF_FALSE$ac_delim
 PKG_CONFIG!$PKG_CONFIG$ac_delim
 ksquirrellibs_CFLAGS!$ksquirrellibs_CFLAGS$ac_delim
 ksquirrellibs_LIBS!$ksquirrellibs_LIBS$ac_delim
@@ -36142,7 +36223,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 69; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 73; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -36749,17 +36830,20 @@ echo
 echo "Results:"
 echo "--------"
 echo
-echo "Version:        ${VERSION}"
+echo "Version:                         ${VERSION}"
+echo "KPart object:                    $have_kpart"
+echo "ksquirrel-libs configurator:     $have_klconf"
 echo
-echo "Compiler:       ${CC}"
-echo "CXXFLAGS:       ${CXXFLAGS}"
+echo "C   compiler:     ${CC}"
+echo "C++ compiler:     ${CXX}"
+echo "CXXFLAGS:         ${CXXFLAGS}"
 echo
-echo "Prefix:         ${prefix}"
-echo "KDE prefix:     ${kde_libs_prefix}"
+echo "Prefix:           ${prefix}"
+echo "KDE prefix:       ${kde_libs_prefix}"
 echo
-echo "KIPI  support:  ${have_kipi}"
-echo "KEXIF support:  ${have_kexif}"
-echo "ASM flags:      ${KSQUIRREL_ASM_DEFS}"
+echo "KIPI  support:    ${have_kipi}"
+echo "KEXIF support:    ${have_kexif}"
+echo "ASM flags:        ${KSQUIRREL_ASM_DEFS}"
 # Check if KDE_SET_PREFIX was called, and --prefix was passed to configure
 if test -n "$kde_libs_prefix" -a -n "$given_prefix"; then
   # And if so, warn when they don't match
