KSquirrel 0.5.0-pre1 sources

diff --git a/configure.in.in b/configure.in.in
--- a/configure.in.in
+++ b/configure.in.in
@@ -1,6 +1,6 @@
 #MIN_CONFIG(3)
 
-AM_INIT_AUTOMAKE(ksquirrel,0.2.8)
+AM_INIT_AUTOMAKE(ksquirrel,0.5.0)
 
 dnl CXXFLAGS="$NOOPT_CXXFLAGS" dnl __kdevelop[noopt]__
 dnl CFLAGS="$NOOPT_CFLAGS" dnl __kdevelop[noopt]__
@@ -9,3 +9,41 @@ CXXFLAGS="$CXXFLAGS $USE_EXCEPTIONS" dnl __kdevelop[exc]__
 dnl KDE_NEED_FLEX dnl __kdevelop__
 dnl AC_PROG_YACC dnl __kdevelop__
 
+
+dnl test opengl
+
+SQ_TST_FILE=test12345.tmp
+
+echo -n "Checking for OpenGL headers..."
+
+cat <<EOF > $SQ_TST_FILE.c
+
+#include <stdio.h>
+#include <GL/gl.h>
+
+int main()
+{
+    return 0;
+}
+EOF
+
+gcc -Wall -Werror ./$SQ_TST_FILE.c -o ./$SQ_TST_FILE > /dev/null 2>&1
+if  test -e "./$SQ_TST_FILE" ; then echo " found"; else rm -f  ./$SQ_TST_FILE.c && echo " not found" && echo "Please install OpenGL headers." && exit 1; fi
+
+rm -f ./$SQ_TST_FILE ./$SQ_TST_FILE.c
+echo -n "Checking for -lGL..."
+
+cat <<EOF > $SQ_TST_FILE.c
+
+#include <stdio.h>
+#include <GL/gl.h>
+
+int main()
+{
+    return 0;
+}
+EOF
+
+gcc -Wall -Werror ./$SQ_TST_FILE.c -o ./$SQ_TST_FILE -lGL > /dev/null 2>&1
+if  test -e "./$SQ_TST_FILE" ; then echo " found"; else rm -f ./$SQ_TST_FILE.c && echo " not found" && echo "Please install OpenGL libraries." && exit 1; fi
+rm -f ./$SQ_TST_FILE ./$SQ_TST_FILE.c
